Feature/sign up button component
isdi-coders-2023/coding-adventure-Marcel-Martino-front-202301-BCN pull request #1
Opened 2023-02-27 16:21 UTC by MarshallTino

Create SignUpButton component
SignUpButton styles
SignUpButton test

2023-02-27 16:24 UTC, catatarelli requested changes

2023-02-27 16:24 UTC, catatarelli commented on src/components/button/SignUpButton.test.tsx
> +      render(<Button text="Sign Up" />);
este text es un magic string

2023-02-27 16:24 UTC, catatarelli commented on src/components/button/SignUpButton.tsx
> +      <button className="signUpButton">{text}</button>
tenemos un button adentro de otro button?

2023-02-27 16:24 UTC, catatarelli commented on src/components/button/SignUpButtonStyled.tsx
> +  left: 18.99px;
este left y top para que sirve?

2023-02-27 16:24 UTC, catatarelli commented on src/components/button/SignUpButtonStyled.tsx
> +  background: #cccf18;
podemos llevarnos los colores a variables o a Theme Provider?

2023-02-28 11:08 UTC, MarshallTino commented on src/components/button/SignUpButtonStyled.tsx
> +  background: #cccf18;
hecho

2023-02-28 11:08 UTC, MarshallTino commented on src/components/button/SignUpButtonStyled.tsx
> +  left: 18.99px;
para nada, lo copie del figma sin mirar , resuelto

2023-02-28 11:09 UTC, MarshallTino commented on src/components/button/SignUpButton.test.tsx
> +      render(<Button text="Sign Up" />);
solucionado!

2023-02-28 11:14 UTC, MarshallTino commented on src/components/button/SignUpButton.test.tsx
> +      render(<Button text="Sign Up" />);
@benjaminrae all done

2023-02-28 11:53 UTC, MMLORENA requested changes

2023-02-28 11:53 UTC, MMLORENA commented on src/components/button/SignUpButton.test.tsx
> +      const button = screen.getByRole("button", { name: "Sign Up" });
Enter

2023-02-28 11:53 UTC, MMLORENA commented on src/components/button/SignUpButton.tsx
> +const SignUpButton = ({ text }: ButtonProps): JSX.Element => {
El nombre del componente debería corresponder con el naming de las props y además qué pasa si mañana cambia el texto del button. ¿Tendría que crear otro componente?

2023-02-28 11:53 UTC, MMLORENA commented on src/components/button/SignUpButtonStyled.tsx
> +  font-family: "Saira Stencil One";
Las fuentes deberían ir en los styles generales o ThemeProvider

2023-02-28 11:53 UTC, MMLORENA commented on src/components/button/SignUpButtonStyled.tsx
> +  font-family: "Saira Stencil One";
Si usas variables las usas también para las fuentes

2023-02-28 12:06 UTC, MarshallTino commented on src/components/button/SignUpButton.test.tsx
> +      const button = screen.getByRole("button", { name: "Sign Up" });
Resuelto

2023-02-28 12:06 UTC, MarshallTino commented on src/components/button/SignUpButton.tsx
> +const SignUpButton = ({ text }: ButtonProps): JSX.Element => {
Cambiado a button.

2023-02-28 12:06 UTC, MarshallTino commented on src/components/button/SignUpButtonStyled.tsx
> +  font-family: "Saira Stencil One";
Hecho tambien.

2023-02-28 12:09 UTC, benjaminrae requested changes

2023-02-28 12:09 UTC, benjaminrae commented on src/components/button/SignUpButtonStyled.tsx
> +const SignUpButtonStyled = styled.button`
Falta separar el import con un enter, y eto no deberia llamarse SignUpButtonStyled.

2023-02-28 12:09 UTC, benjaminrae commented on src/components/button/SignUpButton.tsx
> +    <SignUpButtonStyled className="signUpButton">{text}</SignUpButtonStyled>
Queremos que todos los botones tienen la clase 'signUpButton'? Ademas no escibimos clases en camel case

2023-02-28 12:13 UTC, MarshallTino commented on src/components/button/SignUpButtonStyled.tsx
> +const SignUpButtonStyled = styled.button`
ahora mismo lo arreglo

2023-02-28 12:19 UTC, MMLORENA approved these changes

2023-02-28 12:20 UTC, merged